--- 
repos:

-
  repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks: 
    - 
      id: black
      language_version: python3

# -   repo: local
#     hooks:
#     -   id: python-tests
#         name: pytests
#         entry: pytest tests
#         language: python
#         additional_dependencies: [pre-commit, pytest, pandas, matplotlib, geopandas]
#         always_run: true
#         pass_filenames: false
