service_tags = {
    "leisure": {
        "amenity": ["cinema", "public_bath", "bbq", "nightclub", "casino"],
        "leisure": [
            "bird_hide",
            "picnic_table",
            "dog_park",
            "sauna",
            "fitness_station",
            "swimming_pool",
            "water_park",
            "resort",
        ],
        "tourism": ["zoo", "aquarium", "theme_park"],
    },
    "nature": {
        "leisure": ["park", "beach_resort"],
        "landuse": ["meadow"],
        "natural": ["forest", "beach"],
    },
    "education": {
        "amenity": [
            "childcare",
            "school",
            "university",
            "kindergarten",
            "college",
            "language_school",
            "driving_school",
            "music_school",
            "dancing_school",
            "prep_school",
        ]
    },
    "car": {
        "amenity": ["fuel", "charging_station", "car_wash", "vehicle_inspection"],
        "shop": ["car", "car_repair", "car_parts", "tyres"],
    },
    "accomodation": {
        "tourism": [
            "alpine_hut",
            "caravan_site",
            "motel",
            "hostel",
            "wilderness_hut",
            "camp_site",
            "chalet",
            "apartment",
            "hotel",
            "camp_pitch",
            "guest_house",
        ]
    },
    "culture": {
        "tourism": ["museum", "galery", "artwork"],
        "amenity": [
            "theatre",
            "library",
            "public_bookcase",
            "planetarium",
            "arts_centre",
            "studio",
        ],
    },
    "craft": {
        "craft": [
            "basket_maker",
            "sun_protection",
            "print_shop",
            "sailmaker",
            "carpet_layer",
            "tailor",
            "watchmaker",
            "plasterer",
            "sweep",
            "beekeeper",
            "winery",
            "key_cutter",
            "clockmaker",
            "sculptor",
            "metal_construction",
            "plumber",
            "cabinet_maker",
            "upholsterer",
            "scaffolder",
            "photo_studio",
            "tiler",
            "boatbuilder",
            "mason",
            "heating_engineer",
            "brewery",
            "caterer",
            "cleaning",
            "stand_builder",
            "glass",
            "painter",
            "confectionery",
            "distillery",
            "furniture",
            "photographer",
            "hvac",
            "pottery",
            "leather",
            "window_construction",
            "saddler",
            "floorer",
            "shoemaker",
            "handicraft",
            "builder",
            "roofer",
            "carpenter",
            "signmaker",
            "stonemason",
            "sawmill",
            "bookbinder",
            "dressmaker",
            "glaziery",
            "rigger",
            "tinsmith",
            "joiner",
            "blacksmith",
            "metal_works",
            "laboratory",
            "insulation",
            "gardener",
            "electrician",
            "turner",
            "jeweller",
            "parquet_layer",
            "optician",
            "locksmith",
            "electronics_repair",
            "agricultural_engines",
            "photographic_laboratory",
        ]
    },
    "food": {
        "amenity": [
            "restaurant",
            "fast_food",
            "food_court",
            "cafe",
            "bubble_tea",
            "ice_cream",
            "pub",
            "biergarten",
            "bar",
        ]
    },
    "office": {
        "office": [
            "charity",
            "foundation",
            "advertising_agency",
            "energy_supplier",
            "newspaper",
            "telecommunication",
            "estate_agent",
            "employment_agency",
            "company",
            "notary",
            "tax_advisor",
            "logistics",
            "travel_agent",
            "financial",
            "diplomatic",
            "architect",
            "lawyer",
            "water_utility",
            "cooperative",
            "association",
            "forestry",
            "camping",
            "consulting",
            "administrative",
            "religion",
            "guide",
            "office",
            "educational_institution",
            "accountant",
            "political_party",
            "therapist",
            "research",
            "government",
            "it",
            "vacant",
            "physician",
            "parish",
            "surveyor",
            "insurance",
            "quango",
            "ngo",
            "publisher",
            "moving_company",
            "register",
        ]
    },
    "shop": {
        "amenity": ["vending_machine", "marketplace"],
        "beauty": ["nails"],
        "shop": [
            "organic",
            "outdoor",
            "cheese",
            "hearing_aids",
            "interior_decoration",
            "anime",
            "window_blind",
            "scuba_diving",
            "deli",
            "video",
            "greengrocer",
            "bakery",
            "sports",
            "shoe_repair",
            "wine",
            "perfumery",
            "seafood",
            "boutique",
            "cannabis",
            "computer",
            "laundry",
            "nutrition_supplements",
            "erotic",
            "bag",
            "fabric",
            "mobile_phone",
            "frozen_food",
            "electronics",
            "farm",
            "art",
            "houseware",
            "beverages",
            "newsagent",
            "variety_store",
            "fishing",
            "craft",
            "weapons",
            "department_store",
            "water",
            "baby_goods",
            "tobacco",
            "fireplace",
            "herbalist",
            "wholesale",
            "coffee",
            "kiosk",
            "candles",
            "beauty",
            "hairdresser",
            "shoes",
            "toys",
            "appliance",
            "vacuum_cleaner",
            "furnace",
            "butcher",
            "doors",
            "party",
            "pyrotechnics",
            "health_food",
            "bathroom_furnishing",
            "stationery",
            "carpet",
            "doityourself",
            "bookmaker",
            "kitchen",
            "massage",
            "garden_centre",
            "tiles",
            "fashion",
            "water_sports",
            "security",
            "alcohol",
            "tea",
            "convenience",
            "games",
            "books",
            "funeral_directors",
            "hardware",
            "clothes",
            "hairdresser_supply",
            "music",
            "dry_cleaning",
            "second_hand",
            "paint",
            "copyshop",
            "sewing",
            "florist",
            "gift",
            "hifi",
            "pet_grooming",
            "bed",
            "spices",
            "ticket",
            "hunting",
            "e-cigarette",
            "pastry",
            "chocolate",
            "medical_supply",
            "fashion_accessories",
            "photo",
            "mall",
            "general",
            "cosmetics",
            "tattoo",
            "chemist",
            "watches",
            "electrical",
            "trade",
            "travel_agency",
            "gas",
            "curtain",
            "dairy",
            "video_games",
            "pet",
            "frame",
            "lighting",
            "jewelry",
            "storage_rental",
            "radiotechnics",
            "antiques",
            "lottery",
            "musical_instrument",
            "supermarket",
        ],
    },
}

roads_tags = {
    "highway": [
        "construction",
        "crossing",
        "living_street",
        "motorway",
        "motorway_link",
        "motorway_junction",
        "pedestrian",
        "primary",
        "primary_link",
        "raceway",
        "residential",
        "road",
        "secondary",
        "secondary_link",
        "services",
        "tertiary",
        "tertiary_link",
        "track",
        "trunk",
        "trunk_link",
        "turning_circle",
        "turning_loop",
        "unclassified",
    ],
    "service": ["living_street", "emergency_access"],
}

water_tags = {
    "riverbank": True,
    "reservoir": True,
    "basin": True,
    "dock": True,
    "canal": True,
    "pond": True,
    "natural": ["water", "bay"],
    "waterway": ["river", "canal", "ditch"],
    "landuse": "basin",
}

rail_tags = {"railway": "rail"}
